network:
  _target_: torch.nn.ModuleDict
  modules:
    sequence: 
      _target_: src.models.components.sequence.SequenceModel
      model_name_or_path: facebook/esm2_t33_650M_UR50D #"facebook/esm2_t12_35M_UR50D" facebook/esm2_t33_650M_UR50D
      pooler_type: mean_pooler
      output_dim: 1024
      proj: linear
      use_logit_scale: False
    pocket:
      _target_: src.models.components.structure.StructureModel
      encoder:
        _target_: dig.threedgraph.method.ProNet
        level: backbone
        out_channels: ${model.network.modules.sequence.output_dim}
        euler_noise: True
        data_augment_eachlayer: True 
        dropout: 0.25
      output_dim: ${model.network.modules.sequence.output_dim}
      proj: linear
      use_logit_scale: False
      #pockets: True
      # _target_: src.models.components.pocket.PocketModel
      # #encoder:
      # #  _target_: dig.threedgraph.method.ProNet
      # #  level: backbone
      # #  out_channels: ${model.network.modules.sequence.output_dim}
      # #  euler_noise: True
      # #  data_augment_eachlayer: True 
      # #  dropout: 0.25
      # output_dim: ${model.network.modules.sequence.output_dim}
      # proj: linear
      # use_logit_scale: False
      # ckpt_path: '/p/project/found/bazarova1/pocket_pre_220816.pt'
      # train_enc: False
    struct: 
      _target_: src.models.components.structure.StructureModel
      encoder:
        _target_: dig.threedgraph.method.ProNet
        level: backbone
        out_channels: ${model.network.modules.sequence.output_dim}
        euler_noise: True
        data_augment_eachlayer: True 
        dropout: 0.25
      output_dim: ${model.network.modules.sequence.output_dim}
      proj: linear
      use_logit_scale: False
    text: 
      _target_: src.models.components.text.TextModel
      model_name_or_path: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext #allenai/scibert_scivocab_uncased #microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext #"facebook/esm2_t12_35M_UR50D"
      output_dim: ${model.network.modules.sequence.output_dim}
      pooler_type:  cls_pooler #pooler_output
      proj: linear
      use_logit_scale: False
      use_lora: True
      lora_r: 8
      lora_alpha: 16
      lora_dropout: 0.1
      target_modules: ['query', 'key', 'value']
      frozen: True
    msa: 
      _target_: src.models.components.msa.MsaModel
      pooler_type: mean_pooler
      proj: mlp
      output_dim: ${model.network.modules.sequence.output_dim}
      use_logit_scale: False