_target_: src.models.oneprot_module.ONEPROTLitModule

defaults:
  - network_text.yaml
  #- network_msa.yaml
  - _self_

loss_fn: CLIP
local_loss: True
gather_with_grad: True
compile: False
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
