defaults:
  - default
  - components/sequence
  #- components/struct_token
  - components/struct_graph
  - components/pocket
  - components/text
  #- components/msa

loss_fn: CLIP
local_loss: true
gather_with_grad: true
use_l1_regularization: true
