_target_: src.models.oneprot_module.ONEPROTLitModule
oneprot: 
  _target_: torch.nn.ModuleDict
  modules:
    structure: 
      _target_: src.models.components.structure.StructureModel
      encoder:
        _target_: dig.threedgraph.method.ProNet
        level: aminoacid
        out_channels: 512
        euler_noise: False
        data_augment_eachlayer: False 
        dropout: 0.
      output_dim: 512
      proj: linear
      use_logit_scale: False
    sequence: 
      _target_: src.models.components.sequence.SequenceModel
      model_name_or_path: facebook/esm2_t33_650M_UR50D #"facebook/esm2_t12_35M_UR50D"
      pooler_type: mean_pooler
      output_dim: 512
      proj: linear
      use_logit_scale: False
loss_fn: CLIP
local_loss: True
gather_with_grad: True
compile: False
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
