defaults:
  - default
  - components/sequence
  - components/struct_token
  - components/struct_graph
  - components/pocket
  - components/text
  - components/msa

loss_fn: CLIP
local_loss: True
gather_with_grad: True

