_target_: xgboost.XGBRegressor
name: XGBRegressor
n_estimators: 100
max_depth: 3
learning_rate: 0.1
booster: gbtree
objective: reg:squarederror
eval_metric: rmse
tree_method: auto
n_jobs: -1  # Use all available cores