defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "best"
  monitor: "val/loss_best"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False


model_summary:
  max_depth: 3

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "step"