# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.RichProgressBar.html

rich_progress_bar:
  #_target_: lightning.pytorch.callbacks.TQDMProgressBar
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 1
