# config.yaml

model:
  config_path: /p/project/hai_oneprot/merdivan1/oneprot/logs/train/runs/2024-10-03_12-44-14/config.yaml
  ckpt_path: /p/project/hai_oneprot/merdivan1/oneprot/logs/train/runs/2024-10-03_12-44-14/checkpoints/best.ckpt

dataset:
  csv_file_path: /p/scratch/hai_oneprot/merdivan1/pretrain_dataset/50ss/test_all.csv
  data_dir: /p/scratch/hai_oneprot/merdivan1/pretrain_dataset/50ss/
  max_sequence_length: 1024
  text_max_length: 512
  text_tokenizer: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
  seq_tokenizer: facebook/esm2_t33_650M_UR50D
  remove_hash: true
  msa_model_name_or_path: /p/scratch/hai_oneprot/huggingface/models/msa/esm_msa1b_t12_100M_UR50S.pt
  msa_depth: 50
  max_length: 1024

dataloader:
  batch_size: 50
  shuffle: false
  num_workers: 4

output:
  csv_path: /p/project/hai_oneprot/merdivan1/oneprot/results/retrieval_metrics.csv

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}