defaults:
  - _self_
  - model: oneprot

# Default model settings (will be overridden in the loop)
model:
  name: default
  ckpt_path: null
  config_path: null

esm_model: facebook/esm2_t33_650M_UR50D
tokenizer_name: facebook/esm2_t33_650M_UR50D #westlake-repl/SaProt_650M_AF2 #
saprot_model: westlake-repl/SaProt_650M_AF2

# Output directory
output_dir: "/path/to/output_dir/embeddings/{model_name}"

# Data processing parameters
batch_size: 32
num_workers: 16

# GPU configuration
num_gpus: 4
num_nodes: 2
single_batch_mode: false

# List of model configurations
models:
  # - name: saprot
  - name: awesome_model
    ckpt_path: /path/to/checkpoint/best.ckpt
    config_path: /path/to/config/config.yaml
  # - name: baseline_model
  #   ckpt_path: /path/to/checkpoint/best.ckpt
  #   config_path: /path/to/config/config.yaml  



tasks:
  HumanPPI:
    label_type: "ppi"
    csv_files:
      - /path/to/files/csv_files/HumanPPI/normal_train.csv
      - /path/to/files/csv_files/HumanPPI/normal_valid.csv
      - /path/to/files/csv_files/HumanPPI/normal_test.csv

  GO-BP:
    label_type: "multi-label"
    csv_files:
      - /path/to/files/csv_files/GO/AF2_BP_normal_train.csv
      - /path/to/files/csv_files/GO/AF2_BP_normal_valid.csv
      - /path/to/files/csv_files/GO/AF2_BP_normal_test.csv

  GO-CC:
    label_type: "multi-label"
    csv_files:
      - /path/to/files/csv_files/GO/AF2_CC_normal_train.csv
      - /path/to/files/csv_files/GO/AF2_CC_normal_valid.csv
      - /path/to/files/csv_files/GO/AF2_CC_normal_test.csv

  GO-MF:
    label_type: "multi-label"
    csv_files:
      - /path/to/files/csv_files/GO/AF2_MF_normal_train.csv
      - /path/to/files/csv_files/GO/AF2_MF_normal_valid.csv
      - /path/to/files/csv_files/GO/AF2_MF_normal_test.csv
   
  EC:
    label_type: "multi-label"
    csv_files:
      - /path/to/files/csv_files/EC/AF2_normal_train.csv
      - /path/to/files/csv_files/EC/AF2_normal_valid.csv
      - /path/to/files/csv_files/EC/AF2_normal_test.csv
   
  MetalIonBinding:
    label_type: classification
    csv_files:
      - /path/to/files/csv_files/MetalIonBinding/AF2_normal_train.csv
      - /path/to/files/csv_files/MetalIonBinding/AF2_normal_valid.csv
      - /path/to/files/csv_files/MetalIonBinding/AF2_normal_test.csv
  TopEnzyme:
    label_type: classification
    csv_files:
      - /path/to/files/csv_files/TopEnzyme/Comb826_train_seq.csv
      - /path/to/files/csv_files/TopEnzyme/Comb826_valid_seq.csv
      - /path/to/files/csv_files/TopEnzyme/Comb826_test_seq.csv
  # DeepLoc2:
  #   label_type: classification
  #   csv_files:
  #     - /path/to/files/csv_files/DeepLoc/cls2_normal_train.csv
  #     - /path/to/files/csv_files/DeepLoc/cls2_normal_valid.csv
  #     - /path/to/files/csv_files/DeepLoc/cls2_normal_test.csv
  # DeepLoc10:
  #   label_type: classification
  #   csv_files:
  #     - /path/to/files/csv_files/DeepLoc/cls10_normal_train.csv
  #     - /path/to/files/csv_files/DeepLoc/cls10_normal_valid.csv
  #     - /path/to/files/csv_files/DeepLoc/cls10_normal_test.csv
  # ThermoStability:
  #   label_type: regression
  #   csv_files:
  #     - /path/to/files/csv_files/Thermostability/normal_train.csv
  #     - /path/to/files/csv_files/Thermostability/normal_valid.csv
  #     - /path/to/files/csv_files/Thermostability/normal_test.csv

#for baselines

# tasks:
  # HumanPPI:
  #   label_type: "ppi"
  #   csv_files:
  #     - /path/to/files/saprot_foldseek_data/HumanPPI/foldseek_train.csv
  #     - /path/to/files/saprot_foldseek_data/HumanPPI/foldseek_valid.csv
  #     - /path/to/files/saprot_foldseek_data/HumanPPI/foldseek_test.csv
  
  # GO-BP:
  #   label_type: "multi-label"
  #   csv_files:
  #     - /path/to/files/saprot_foldseek_data/GO/AF2_BP_foldseek_train.csv
  #     - /path/to/files/saprot_foldseek_data/GO/AF2_BP_foldseek_valid.csv
  #     - /path/to/files/saprot_foldseek_data/GO/AF2_BP_foldseek_test.csv
  
  # GO-CC:
  #   label_type: "multi-label"
  #   csv_files:
  #     - /path/to/files/saprot_foldseek_data/GO/AF2_CC_foldseek_train.csv
  #     - /path/to/files/saprot_foldseek_data/GO/AF2_CC_foldseek_valid.csv
  #     - /path/to/files/saprot_foldseek_data/GO/AF2_CC_foldseek_test.csv
  
  # GO-MF:
  #   label_type: "multi-label"
  #   csv_files:
  #     - /path/to/files/saprot_foldseek_data/GO/AF2_MF_foldseek_train.csv
  #     - /path/to/files/saprot_foldseek_data/GO/AF2_MF_foldseek_valid.csv
  #     - /path/to/files/saprot_foldseek_data/GO/AF2_MF_foldseek_test.csv
  
  # EC:
  #   label_type: "multi-label"
  #   csv_files:
  #     - /path/to/files/saprot_foldseek_data/EC/AF2_foldseek_train.csv
  #     - /path/to/files/saprot_foldseek_data/EC/AF2_foldseek_valid.csv
  #     - /path/to/files/saprot_foldseek_data/EC/AF2_foldseek_test.csv
  
  # MetalIonBinding:
  #   label_type: classification
  #   csv_files:
  #     - /path/to/files/saprot_foldseek_data/MetalIonBinding/AF2_foldseek_train.csv
  #     - /path/to/files/saprot_foldseek_data/MetalIonBinding/AF2_foldseek_valid.csv
  #     - /path/to/files/saprot_foldseek_data/MetalIonBinding/AF2_foldseek_test.csv    
  # DeepLoc2:
  #   label_type: classification
  #   csv_files:
  #     - /path/to/files/saprot_foldseek_data/DeepLoc/cls2_foldseek_train.csv
  #     - /path/to/files/saprot_foldseek_data/DeepLoc/cls2_foldseek_valid.csv
  #     - /path/to/files/saprot_foldseek_data/DeepLoc/cls2_foldseek_test.csv
  # DeepLoc10:
  #   label_type: classification
  #   csv_files:
  #     - /path/to/files/saprot_foldseek_data/DeepLoc/cls10_foldseek_train.csv
  #     - /path/to/files/saprot_foldseek_data/DeepLoc/cls10_foldseek_valid.csv
  #     - /path/to/files/saprot_foldseek_data/DeepLoc/cls10_foldseek_test.csv
  # ThermoStability:
  #   label_type: regression
  #   csv_files:
  #     - /path/to/files/saprot_foldseek_data/Thermostability/foldseek_train.csv
  #     - /path/to/files/saprot_foldseek_data/Thermostability/foldseek_valid.csv
  #     - /path/to/files/saprot_foldseek_data/Thermostability/foldseek_test.csv

