defaults:
  - _self_
  - model: oneprot
  - classifier: knn

encode_batch_size: 10
ckpt_path: /p/project/hai_oneprot/bazarova1/oneprot-main/slurms/manual_ckpts/2024-07-03__09:36:19/last.ckpt
batch_limit: 1.0
evaluate_on: ["train", "val", "test"]
shuffle: False
output_dir: /p/project/hai_oneprot/sommer3/oneprot/outputs/alina_ckpt_best
transform_func: identity # threshold
bit_threshold: 0

# classifier
fit_classifier_on: "seq" # "struct", "both"
