defaults:
  - _self_
  - model: oneprot
  - classifier: logistic_regression
  - regressor: linear_regression

encode_batch_size: 10
ckpt_path: null
batch_limit: 1.0
evaluate_on: ["train", "val", "test"]
shuffle: False
output_dir: /p/project/hai_oneprot/floege1/oneprot-2/outputs/saprot/esm2_baseline #test_ckpt/
transform_func: identity # threshold_0
task_name: MetalIonBinding
fit_classifier_on: "seq" # "struct", "both"
 