defaults:
  - data: oneprot
  - model: oneprot
  - logger: wandb
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - _self_

task_name: "cross_modality_retrieval"
tags: ${data.data_modalities}

# Checkpoint path for the trained model
ckpt_path: null

# Retrieval dataset path
retrieval_dataset: "/path/to/retrieval/dataset"

# Evaluation parameters
eval_ks: [1, 5, 10]
batch_size: 32
num_workers: 4
pin_memory: True

# Embedding transformation function
transform_func: "identity"  # Options: "identity", "threshold"
bit_threshold: 0.5  # Only used if transform_func is "threshold"

# seed for random number generators
seed: 1881