# saprot_fit_pytorch.yaml

defaults:
  - _self_
  - override hydra/sweeper: basic

evaluate_on: ["train", "valid", "test"]
emb_dir: /p/project/hai_oneprot/merdivan1/oneprot/embeddings/
results_dir: /p/project/hai_oneprot/merdivan1/oneprot/results/


# Model configuration
model:
  input_dim: 1280  # Adjust based on your embedding size
  hidden_dim: 256
  learning_rate: 0.001
  batch_size: 32
  max_epochs: 10
  early_stopping_patience: 10

threshold: .inf

task_name: EC
model_type: esm2
downstream_model:
  name: MLP
# Sweep parameters
sweep:
  learning_rate: [0.001, 0.01]
  batch_size: [128]
  max_epochs: [250, 500, 1000]
  task_name: ["TopEnzyme"] #,"HumanPPI","EC","GO-BP","GO-MF","GO-CC","ThermoStability","DeepLoc2","DeepLoc10","TopEnzyme"]
  #, "MetalIonBinding","EC","GO-BP","GO-MF","GO-CC","ThermoStability","DeepLoc2","DeepLoc10","TopEnzyme"]
  model_type: [esm2, oneprot]

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}