defaults:
  - _self_
  - model: oneprot
  - classifier: knn

encode_batch_size: 10
ckpt_path: null
batch_limit: 1.0
evaluate_on: ["train", "val", "test"]
shuffle: False
output_dir: /p/project/hai_oneprot/sommer3/oneprot/outputs/saprot/test_ckpt/
transform_func: identity # threshold_0
task_name: DeepLoc_cls2
fit_classifier_on: "seq" # "struct", "both"
