defaults:
  - _self_
  - model: oneprot
  - classifier: logistic_regression
  - regressor: gradient_boosting_regressor

encode_batch_size: 10
ckpt_path: null
batch_limit: 1.0
evaluate_on: ["train", "val", "test"]
shuffle: False
oneprot_output_dir: /p/project/hai_oneprot/floege1/oneprot-2/outputs/saprot/30ss #test_ckpt/
esm2_output_dir: /p/project/hai_oneprot/floege1/oneprot-2/outputs/saprot/esm2_baseline/
results_dir: /p/project/hai_oneprot/floege1/oneprot-2/results/
system: OneProt # "OneProt", "ESM2"
transform_func: identity # threshold_0
task_name: MetalIonBinding
fit_classifier_on: "seq" # "struct", "both"                #needs to be seq for ESM Baseline!!!
hyperparameter_search: True
  