text:
  _target_: src.models.components.text_encoder.TextEncoder
  model_name_or_path: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
  output_dim: ${..sequence.output_dim}
  pooling_type: cls
  proj_type: mlp
  use_lora: False
  lora_r: 8
  lora_alpha: 8
  lora_dropout: 0.1
  lora_target_modules: ['query', 'key', 'value']
  frozen: true
  use_logit_scale: true
  learnable_logit_scale: false